development: &default
  adapter: 'postgresql'
  encoding: 'utf8'
  database: 'inspinia_development'
  host: 'localhost'
  username: postgres
  port: 5432
  password: ''
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 55 } %>

test:
  <<: *default
  database: 'inspinia_test'
